apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: allow-volume-expansion
provisioner: hostpath.csi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
